### ISSUE TITLE
[nextjs-api-dev-proxy] - allow on specific env

### ISSUE THREAD

**Issue by isBatak** [infinum/react-nuts-and-bolts#15]
We should add a config opt-in to proxy for specific environment.
https://github.com/infinum/react-nuts-and-bolts/blob/1adf9ff38a520060f48c1eb9ae0fd63fc971d5ca/packages/nextjs-api-dev-proxy/src/nextjs-api-dev-proxy.ts#L38

API proposal:
```
export default createProxy(process.env.API_URL, {
	shouldDisableProxy: () => {
	   return process.env. NEXT_PUBLIC_NEXT_APP_ENV === 'production';
	}
});

const isDisabled = options.shouldDisableProxy ? options.shouldDisableProxy() : process.env.NODE_ENV !== 'development';
if (isDisabled) {
  return res.status(404).json({ message: 'Not found' });
};
```

todo:
- [ ] rethink `shouldDisableProxy` option naming 
- [ ] should `shouldDisableProxy` be of type `boolean | () => boolean`
- [ ] should default `shouldDisableProxy` value be `process.env.NODE_ENV !== 'development'`, this will simplify `isDisabled` expression.

**Comment by kristian240** [comment]
>  rethink `shouldDisableProxy` option naming

I think simple `disabled` will do the trick. We can add more info using JSDoc.

> should `shouldDisableProxy` be of type `boolean | () => boolean`

I'm okay with that being either a boolean or a function that returns a boolean. What do you think about allowing async values as well? 

`boolean | () => boolean | Promise<boolean> | () => Promise<boolean>`

>  should default `shouldDisableProxy` value be `process.env.NODE_ENV !== 'development'`, this will simplify `isDisabled` expression.

I would still keep the current behaviour to avoid breaking changes.

**Comment by isBatak** [comment]
> What do you think about allowing async values as well?
We can add support for async fn later if we find a need for it.
